### PR TITLE
Updating class attribute names to move away from property decorators …

### PR DESCRIPTION
**Pull request by nlahaye**
…to a naming convention that allows for multi-GPU training via PyTorch

### CODE REVIEW

**Comment by nlahaye** [comment]
Will push changes to fix tests associated with initial changes this week.

**Comment by gugarosa** [comment]
Hi Nick! First of all, thank you for making the changes and submitting a PR.

I was wondering, what would happen if, instead, we remove the `torch.Tensor` checking in the property decorators? Would this be enough for working with multi-GPU?

My worry is that renaming the variables themselves will introduces errors for everyone that is currently accessing the variables, for example, we would have a `_W` instead of a `W`.

Best regards,
Gustavo.

**Comment by nlahaye** [comment]
Hi Gustavo,
    Thanks for the suggestion! I will run some tests to see if this will work. I will let you know ASAP. I think I tried this previously, but I do not remember for sure.
    
I hope all is well!
Nick

**Comment by gugarosa** [comment]
> Hi Gustavo, Thanks for the suggestion! I will run some tests to see if this will work. I will let you know ASAP. I think I tried this previously, but I do not remember for sure.
> 
> I hope all is well! Nick

No worries, take your time! I appreciate all the effort you are putting in making the package more useful for everyone!

**Comment by gugarosa** [comment]
The latest comitts sounds great! Let me know whenever I can merge them and do not worry about the Travis build error. For some reason, pip is failing with Python 3.7.

**Comment by nlahaye** [comment]
Hey @gugarosa 

I hope you are doing well! 

I finally got a chance to test the recommended changes, and it looks like it works!

I pushed the changes, but I am having an issue with the CI's python3.7 build. I tested in a local python3.7 env and am not having the same issue. 

It looks like the last build on the master branch was 5 months ago, are you able to test to see if the same issue shows up there?

Thanks!
Nick

**Comment by nlahaye** [comment]
Oh, sorry. Looks like I missed your last message. Everything is good to merge when you are ready.

Thanks!!

**Pull request merged**
